excluded: Pods
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - line_length
  - opening_brace
  - todo
  - type_body_length
  - variable_name
